name: Deploy to cPanel

on:
  push:
    branches:
      - master   # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Set your private key in GitHub Secrets

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH with passphrase
      run: |
        sshpass -p "${{ secrets.SSH_PASSPHRASE }}" ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"


    - name: Deploy to cPanel
      run: |
        ssh -o StrictHostKeyChecking=no leesuqgj@198.54.116.2 "
          cd public_html && git pull origin main && npm install && npm run build"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
